// <auto-generated />
using Faculty.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Faculty.Migrations.NoticeDb
{
    [DbContext(typeof(NoticeDbContext))]
    partial class NoticeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Faculty.Models.Notice", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NoticeDate");

                    b.Property<string>("NoticeDescription")
                        .IsRequired();

                    b.Property<string>("NoticeShortTitle")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Notices");
                });
#pragma warning restore 612, 618
        }
    }
}
