// <auto-generated />
using Faculty.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Faculty.Migrations.PublicationDb
{
    [DbContext(typeof(PublicationDbContext))]
    [Migration("20181023154741_InitPublication")]
    partial class InitPublication
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Faculty.Models.Publications", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PublicationLink");

                    b.Property<string>("PublicationTitle");

                    b.Property<string>("PublicationType");

                    b.Property<string>("PublicationYear");

                    b.HasKey("ID");

                    b.ToTable("Publications");
                });
#pragma warning restore 612, 618
        }
    }
}
