// <auto-generated />
using Faculty.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Faculty.Migrations.CourseDb
{
    [DbContext(typeof(CourseDbContext))]
    partial class CourseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Faculty.Models.Course", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CourseCode");

                    b.Property<string>("CourseDescription");

                    b.Property<string>("CourseSemester");

                    b.Property<string>("CourseTitle");

                    b.Property<string>("CourseYear");

                    b.Property<int>("DeadLineMonth");

                    b.Property<int>("DeadlineDay");

                    b.Property<string>("DeadlineTime");

                    b.Property<int>("DeadlineYear");

                    b.Property<string>("ExamInstructions");

                    b.Property<string>("Instructor");

                    b.Property<string>("LecturesTiming");

                    b.Property<string>("StudentDeclined");

                    b.Property<string>("StudentRegistered");

                    b.Property<string>("StudentsApproved");

                    b.Property<int>("SupervisorID");

                    b.Property<string>("TeachingAssistants");

                    b.HasKey("ID");

                    b.ToTable("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
