// <auto-generated />
using Faculty.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Faculty.Migrations.PhdStudentsDb
{
    [DbContext(typeof(PhdStudentsDbContext))]
    [Migration("20181029084839_third")]
    partial class third
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Faculty.Models.PhdStudents", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("College");

                    b.Property<string>("DegreeCompletion");

                    b.Property<string>("DegreeStatus");

                    b.Property<string>("StudentName");

                    b.Property<int>("SupervisorID");

                    b.Property<string>("ThesisTitle");

                    b.HasKey("ID");

                    b.ToTable("PhdStudents");
                });
#pragma warning restore 612, 618
        }
    }
}
