// <auto-generated />
using Faculty.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Faculty.Migrations.ProfileDb
{
    [DbContext(typeof(ProfileDbContext))]
    [Migration("20181029084929_fourth")]
    partial class fourth
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Faculty.Models.Profile", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Achievements");

                    b.Property<string>("AreasOfInterest")
                        .IsRequired();

                    b.Property<string>("College")
                        .IsRequired();

                    b.Property<string>("Department")
                        .IsRequired();

                    b.Property<string>("Designation")
                        .IsRequired();

                    b.Property<string>("DoctoratesDegreeDetails");

                    b.Property<string>("EmailID")
                        .IsRequired();

                    b.Property<string>("FullName")
                        .IsRequired();

                    b.Property<string>("GoogleScholarLink");

                    b.Property<string>("LoginEmailID");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(10);

                    b.Property<string>("PostGraduateDegreeDetails");

                    b.Property<string>("ProfessionalExperience");

                    b.Property<string>("ProfilePic");

                    b.Property<string>("ShortBio");

                    b.Property<string>("UnderGraduateDegreeDetails");

                    b.HasKey("ID");

                    b.ToTable("Profiles");
                });
#pragma warning restore 612, 618
        }
    }
}
