// <auto-generated />
using Faculty.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Faculty.Migrations.CourseResourceDb
{
    [DbContext(typeof(CourseResourceDbContext))]
    partial class CourseResourceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Faculty.Models.CourseResource", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CourseID");

                    b.Property<string>("CourseName");

                    b.Property<string>("ResourceLink");

                    b.Property<string>("ResourceTitle");

                    b.Property<string>("SubmissionDirectoryLink");

                    b.HasKey("ID");

                    b.ToTable("Resources");
                });
#pragma warning restore 612, 618
        }
    }
}
